// Generated by scripts/deployment-manifest.mjs. Do not edit by hand.
export const DEPLOYMENTS = {
  "31337": {
    "schemaVersion": 2,
    "chainId": 31337,
    "chainName": "Local Anvil",
    "status": "deployed",
    "rpcUrl": "http://127.0.0.1:8545",
    "contracts": {
      "agentRegistry": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      "reputationHub": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      "guaranteeEscrow": "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
      "schellingVoting": "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9"
    },
    "runtimeBytecodeHashes": {
      "agentRegistry": "0xe7f8c873823519aa5715ce40951ecf6d9798fcc28a4b6a95894a152e4c6e8a76",
      "reputationHub": "0x97d8f0ea00a4213196ec249cf24fd4fc8a9381074ecebcae010f3ce669f8c4c2",
      "guaranteeEscrow": "0x127d9b5fa9a43c0107d434f9b066fc4d6b93d4245be8becc02b31f95cd1e6454",
      "schellingVoting": "0x862d8a7c6972b25425a5c9780445042178b15e7eb3ecf767250c6929b0733889"
    },
    "deploymentMetadata": {
      "agentRegistry": {
        "constructorArgs": [],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x5df23832bbcb6bda6ce985e7dd10f6e2ca0729b99253118d9ffbd0c6732eef92",
        "blockNumber": 1
      },
      "reputationHub": {
        "constructorArgs": [],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x94d5c99f87079d33e65c56c4189166a01c09803c9b09aea65dddad888950e1f5",
        "blockNumber": 2
      },
      "guaranteeEscrow": {
        "constructorArgs": [
          "0x5FbDB2315678afecb367f032d93F642f64180aa3",
          "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
        ],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x78b7bb5ba92494b85c8870091e36f8dd5d6362144cdbbe3c790d83ea8ed3493a",
        "blockNumber": 2
      },
      "schellingVoting": {
        "constructorArgs": [
          "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
          "0x5FbDB2315678afecb367f032d93F642f64180aa3",
          "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
          "100000000000000000",
          "86400",
          "86400"
        ],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x04b33f0ca39eb98c4b6aa19c30be12c0bf60dbe6a3f14b2ad35b7da581206069",
        "blockNumber": 4
      }
    },
    "votingParameters": {
      "caseStake": "100000000000000000",
      "commitWindow": 86400,
      "revealWindow": 86400
    }
  },
  "84532": {
    "schemaVersion": 2,
    "chainId": 84532,
    "chainName": "Base Sepolia",
    "status": "undeployed",
    "rpcUrl": "https://sepolia.base.org",
    "contracts": {
      "agentRegistry": "0x0000000000000000000000000000000000000000",
      "reputationHub": "0x0000000000000000000000000000000000000000",
      "guaranteeEscrow": "0x0000000000000000000000000000000000000000",
      "schellingVoting": "0x0000000000000000000000000000000000000000"
    },
    "runtimeBytecodeHashes": {
      "agentRegistry": null,
      "reputationHub": null,
      "guaranteeEscrow": null,
      "schellingVoting": null
    },
    "deploymentMetadata": {
      "agentRegistry": null,
      "reputationHub": null,
      "guaranteeEscrow": null,
      "schellingVoting": null
    },
    "votingParameters": {
      "caseStake": "100000000000000000",
      "commitWindow": 86400,
      "revealWindow": 86400
    }
  }
} as const;

export type DeploymentChainId = keyof typeof DEPLOYMENTS;
export type Deployment = (typeof DEPLOYMENTS)[DeploymentChainId];
export type DeploymentContracts = {
  readonly agentRegistry: `0x${string}`;
  readonly reputationHub: `0x${string}`;
  readonly guaranteeEscrow: `0x${string}`;
  readonly schellingVoting: `0x${string}`;
};
