// Generated by scripts/deployment-manifest.mjs. Do not edit by hand.
export const DEPLOYMENTS = {
  "31337": {
    "schemaVersion": 2,
    "chainId": 31337,
    "chainName": "Local Anvil",
    "status": "deployed",
    "rpcUrl": "http://127.0.0.1:18545",
    "contracts": {
      "agentRegistry": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      "reputationHub": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      "guaranteeEscrow": "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
      "schellingVoting": "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9"
    },
    "runtimeBytecodeHashes": {
      "agentRegistry": "0x49c049bd856426368333a934ba7c6c33b643ed437451a65439d4760161765d70",
      "reputationHub": "0x97d8f0ea00a4213196ec249cf24fd4fc8a9381074ecebcae010f3ce669f8c4c2",
      "guaranteeEscrow": "0xc80e8bf5242ff6cea2bd6173832b4f7bd902eb26e121f357ceefb696b886b937",
      "schellingVoting": "0x93c51e89b945b190717ac75b1cbfa038f002211cee5cb7811323fc4320681238"
    },
    "deploymentMetadata": {
      "agentRegistry": {
        "constructorArgs": [],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0xcc61454122ece19a90d5029253bb722a7c1d9341dd6990c679ec1e0aa5170ed0",
        "blockNumber": 1
      },
      "reputationHub": {
        "constructorArgs": [],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x94d5c99f87079d33e65c56c4189166a01c09803c9b09aea65dddad888950e1f5",
        "blockNumber": 2
      },
      "guaranteeEscrow": {
        "constructorArgs": [
          "0x5FbDB2315678afecb367f032d93F642f64180aa3",
          "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
        ],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x158395edb913e330a1a48fd5d0f87a0280b99cca14c282f5f6f2ff50498a54cf",
        "blockNumber": 2
      },
      "schellingVoting": {
        "constructorArgs": [
          "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
          "0x5FbDB2315678afecb367f032d93F642f64180aa3",
          "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
          "100000000000000000",
          "86400",
          "86400"
        ],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0xd7eb8862a8897d9a85eeacab73ec6f1d5d2daf099affd49acfc99fd545341c14",
        "blockNumber": 2
      }
    },
    "votingParameters": {
      "caseStake": "100000000000000000",
      "commitWindow": 86400,
      "revealWindow": 86400
    }
  },
  "84532": {
    "schemaVersion": 2,
    "chainId": 84532,
    "chainName": "Base Sepolia",
    "status": "undeployed",
    "rpcUrl": "https://sepolia.base.org",
    "contracts": {
      "agentRegistry": "0x0000000000000000000000000000000000000000",
      "reputationHub": "0x0000000000000000000000000000000000000000",
      "guaranteeEscrow": "0x0000000000000000000000000000000000000000",
      "schellingVoting": "0x0000000000000000000000000000000000000000"
    },
    "runtimeBytecodeHashes": {
      "agentRegistry": null,
      "reputationHub": null,
      "guaranteeEscrow": null,
      "schellingVoting": null
    },
    "deploymentMetadata": {
      "agentRegistry": null,
      "reputationHub": null,
      "guaranteeEscrow": null,
      "schellingVoting": null
    },
    "votingParameters": {
      "caseStake": "100000000000000000",
      "commitWindow": 86400,
      "revealWindow": 86400
    }
  }
} as const;

export type DeploymentChainId = keyof typeof DEPLOYMENTS;
export type Deployment = (typeof DEPLOYMENTS)[DeploymentChainId];
export type DeploymentContracts = {
  readonly agentRegistry: `0x${string}`;
  readonly reputationHub: `0x${string}`;
  readonly guaranteeEscrow: `0x${string}`;
  readonly schellingVoting: `0x${string}`;
};
