// Generated by scripts/deployment-manifest.mjs. Do not edit by hand.
export const DEPLOYMENTS = {
  "31337": {
    "schemaVersion": 2,
    "chainId": 31337,
    "chainName": "Local Anvil",
    "status": "deployed",
    "rpcUrl": "http://127.0.0.1:8545",
    "contracts": {
      "agentRegistry": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      "reputationHub": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      "guaranteeEscrow": "0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0",
      "schellingVoting": "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9"
    },
    "runtimeBytecodeHashes": {
      "agentRegistry": "0x7aacd9d7df97a3f3b412b3e6e4354559bc0e2306c7e50e41e42ce2596c56739f",
      "reputationHub": "0x97d8f0ea00a4213196ec249cf24fd4fc8a9381074ecebcae010f3ce669f8c4c2",
      "guaranteeEscrow": "0x69898b3019f14410e8e788ceff867c1dd02da16b3f0b36adce495cc2b4e6b1ef",
      "schellingVoting": "0x80604a2dbe2f4659d6be2cf643d539c36f21c1281c50e271351df9184c47fb01"
    },
    "deploymentMetadata": {
      "agentRegistry": {
        "constructorArgs": [],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0xf23f058abdee44045691013fb5f642090c2a9213a578ce25e95cc3a4ddd4ae24",
        "blockNumber": 1
      },
      "reputationHub": {
        "constructorArgs": [],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x94d5c99f87079d33e65c56c4189166a01c09803c9b09aea65dddad888950e1f5",
        "blockNumber": 2
      },
      "guaranteeEscrow": {
        "constructorArgs": [
          "0x5FbDB2315678afecb367f032d93F642f64180aa3",
          "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
        ],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0x66af8208606a08902e611a9aa1ed4211b6f56424eb3f5c49e03363f00d30f027",
        "blockNumber": 3
      },
      "schellingVoting": {
        "constructorArgs": [
          "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
          "0x5FbDB2315678afecb367f032d93F642f64180aa3",
          "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
          "100000000000000000",
          "86400",
          "86400"
        ],
        "deployer": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "transactionHash": "0xc38571a502dd1d28f7820dbf5a34eb6b9977cda9a9694e9cd76edad595701e98",
        "blockNumber": 3
      }
    },
    "votingParameters": {
      "caseStake": "100000000000000000",
      "commitWindow": 86400,
      "revealWindow": 86400
    }
  },
  "84532": {
    "schemaVersion": 2,
    "chainId": 84532,
    "chainName": "Base Sepolia",
    "status": "undeployed",
    "rpcUrl": "https://sepolia.base.org",
    "contracts": {
      "agentRegistry": "0x0000000000000000000000000000000000000000",
      "reputationHub": "0x0000000000000000000000000000000000000000",
      "guaranteeEscrow": "0x0000000000000000000000000000000000000000",
      "schellingVoting": "0x0000000000000000000000000000000000000000"
    },
    "runtimeBytecodeHashes": {
      "agentRegistry": null,
      "reputationHub": null,
      "guaranteeEscrow": null,
      "schellingVoting": null
    },
    "deploymentMetadata": {
      "agentRegistry": null,
      "reputationHub": null,
      "guaranteeEscrow": null,
      "schellingVoting": null
    },
    "votingParameters": {
      "caseStake": "100000000000000000",
      "commitWindow": 86400,
      "revealWindow": 86400
    }
  }
} as const;

export type DeploymentChainId = keyof typeof DEPLOYMENTS;
export type Deployment = (typeof DEPLOYMENTS)[DeploymentChainId];
export type DeploymentContracts = {
  readonly agentRegistry: `0x${string}`;
  readonly reputationHub: `0x${string}`;
  readonly guaranteeEscrow: `0x${string}`;
  readonly schellingVoting: `0x${string}`;
};
